App\Domain\User\Entity\User:
  type: entity
  table: users
  repositoryClass: App\Infrastructure\Repository\UserRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    fullName:
      type: string
      length: 255
    dateOfBirth:
      type: date
    document:
      type: string
      length: 16
    createdAt:
      type: datetime
    updatedAt:
      type: datetime
      nullable: true